version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
volumes:
  mongo_data: {}